[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "BMX"
name = "HighEffortScrapPosts"
description = "We spend too much time on the computer."
websiteUrl = "https://github.com/Xilophor/HighEffortScrapPosts"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.13.2"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../HighEffortScrapPosts/bin/Release/netstandard2.1/HighEffortScrapPosts.dll"
target = "/BepInEx/plugins/HighEffortScrapPosts/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "mods", "items" ]